language: rust
rust:
  - stable
os:
  - linux
  - osx
  - windows

addons:
  apt:
    packages:
      - uuid-dev

cache:
  - cargo

before_script:
  - rustup update
  - rustup component add clippy
  - rustup component add rustfmt

script:
  - cd aeron_driver-sys
  - cargo test
  - cargo test --release
  - cargo test --features "static"

  - cd ..
  - cargo test
  - cargo test --release
  - cargo clippy --all
  - cargo fmt --all -- --check
