language: rust
rust:
  - stable
os:
  - linux
  - osx
  - windows

cache:
  - cargo

before_script:
  - rustup update
  - rustup component add clippy
  - rustup component add rustfmt

script:
  - cargo test --no-run
  - cargo test
  - cargo test --release --no-run
  - cargo test --release

  - cd aeron_driver-sys/
  - cargo test --features "static"

  - cd ..
  - cargo clippy --all
  - cargo fmt --all -- --check

branches:
  only:
    - master
    - staging
    - trying
    
