language: rust
rust:
  - stable
os:
  - linux
  - osx
  - windows

cache:
  - cargo

before_script:
  - rustup set profile minimal
  - rustup update
  - rustup component add clippy
  - rustup component add rustfmt
  # CMake doesn't like `sh.exe` being available on Windows,
  # and since we don't use it elsewhere, just remove from PATH
  - export PATH="${PATH/:\/bin/}"

script:
  - cargo clippy --all
  - cargo fmt --all -- --check

  - cargo test --no-run
  - cargo test
  - cargo test --release --no-run
  - cargo test --release

  - cd aeron-driver-sys/
  - cargo test --features "static"

branches:
  only:
    - master
    - staging
    - trying
    
