[package]
name = "aeron-driver-sys"
version = "1.0.0+1.25.0"
authors = ["Bradlee Speice <bradlee@speice.io>"]
edition = "2018"
links = "aeron_driver"
build = "build.rs"

[dependencies]

[build-dependencies]
bindgen = "0.51"
cmake = "0.1"
dunce = "1.0.0"

[features]
static = []
